version: 2.1
orbs:
  utils: ethereum-optimism/circleci-utils@1.0.14


jobs:
  close-issue:
    machine:
      image: ubuntu-2204:2024.08.1
    parameters:
      label_name:
        type: string
      message:
        type: string
    steps:
      - utils/get-webhook-payload:
          webhook_body: << pipeline.trigger_parameters.webhook.body >>
          webhook_file: "payload.json"
      - run:
          name: Close issue if label is added
          command: |

            ACTION=$(cat payload.json | jq -r '.action')
            ISSUE_NUMBER=$(cat payload.json| jq -r '.issue.number')
            LABEL_NAME=$(cat payload.json | jq -r '.label.name')

            echo "Closing issue $ISSUE_NUMBER if label $LABEL_NAME is added on repository ${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}"

            if [ ! -z "$ISSUE_NUMBER" ] && [ "$LABEL_NAME" = "<< parameters.label_name >>" ] && [ "$ACTION" = "labeled" ]; then
                MESSAGE="<< parameters.message >>"
                export GH_TOKEN=$GITHUB_TOKEN_GOVERNANCE
                gh issue close --repo "${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}" "$ISSUE_NUMBER" --comment "$MESSAGE"
            fi

workflows:
  webhook-workflow:
    jobs:
      - close-issue:
         label_name: "auto-close-trivial-contribution"
         message: "Thank you for your interest in contributing!
                At this time, we are not accepting contributions that primarily fix spelling, stylistic, or grammatical errors in documentation, code, or elsewhere.
                Please check our [contribution guidelines](https://github.com/ethereum-optimism/optimism/blob/develop/CONTRIBUTING.md#contributions-related-to-spelling-and-grammar) for more information.
                This issue will be closed now."
         context:
          - circleci-repo-optimism
